const alphabet = {
  a: { codeword: "Alpha",     faa: "AL FAH", ipa: ""},
  b: { codeword: "Bravo",     faa: "BRAH VOH", ipa: ""},
  c: { codeword: "Charlie",   faa: "CHAR LEE", ipa: ""},
  d: { codeword: "Delta",     faa: "DELL TAH, ipa: ""},
  e: { codeword: "Echo",      faa: "ECK OH", ipa: ""},
  f: { codeword: "Foxtrot",   faa: "FOKS TROT", ipa: ""},
  g: { codeword: "Golf",      faa: "GOLF", ipa: ""},
  h: { codeword: "Hotel",     faa: "HOH TELL", ipa: ""},
  i: { codeword: "India",     faa: "IN DEE AH", ipa: ""},
  j: { codeword: "Juliett",   faa: "JEW LEE ETT", ipa: ""},
  k: { codeword: "Kilo",      faa: "KEY LOH", ipa: ""},
  l: { codeword: "Lima",      faa: "LEE MAH", ipa: ""},
  m: { codeword: "Mike",      faa: "MIKE", ipa: ""},
  n: { codeword: "November",  faa: "NO VEM BER", ipa: ""},
  o: { codeword: "Oscar",     faa: "OSS CUR", ipa: ""},
  p: { codeword: "Papa",      faa: "PAH PAH", ipa: ""},
  q: { codeword: "Quebec",    faa: "KEH BECK", ipa: ""},
  r: { codeword: "Romeo",     faa: "ROW ME OH", ipa: ""},
  s: { codeword: "Sierra",    faa: "SEE AIR RAH", ipa: ""},
  t: { codeword: "Tango",     faa: "TANG OH", ipa: ""},
  u: { codeword: "Uniform",   faa: "YOU NEE FORM", ipa: ""},
  v: { codeword: "Victor",    faa: "VIK TAH", ipa: ""},
  w: { codeword: "Whiskey",   faa: "WISS KEY", ipa: ""},
  x: { codeword: "X-Ray",     faa: "ECKS RAY", ipa: ""},
  y: { codeword: "Yankee",    faa: "YANG KEY", ipa: ""},
  z: { codeword: "Zulu",      faa: "ZOO LOO", ipa: ""},
  1: { codeword: "UNAONE",    faa: "OO-NAH-WUN", ipa: ""},
  2: { codeword: "BISSOTWO",  faa: "BEES-SOH-TOO", ipa: ""},
  3: { codeword: "TERRATHREE",faa: "TAY-RAH-TREE", ipa: ""},
  4: { codeword: "KARTEFOUR", faa: "KAR-TAY-FOWER", ipa: ""},
  5: { codeword: "PANTAFIVE", faa: "PAN-TAH-FIVE", ipa: ""},
  6: { codeword: "SOXISIX",   faa: "SOK-SEE-SIX", ipa: ""},
  7: { codeword: "SETTESEVEN",faa: "SAY-TAY-SEVEN", ipa: ""},
  8: { codeword: "OKTOEIGHT", faa: "OK-TOH-AIT", ipa: ""},
  9: { codeword: "NOVENINE",  faa: "NO-VAY-NINER", ipa: ""},
  0: { codeword: "NADAZERO",  faa: "NAH-DAH-ZAY-ROH", ipa: ""},

  ".": ["STOP", "STOP"]
};

export default alphabet;