const alphabet = {
  a: { codeword: "alpha",       faa: "AL FAH",          ipa: "" },
  b: { codeword: "bravo",       faa: "BRAH VOH",        ipa: "" },
  c: { codeword: "charlie",     faa: "CHAR LEE",        ipa: "" },
  d: { codeword: "delta",       faa: "DELL TAH",        ipa: "" },
  e: { codeword: "echo",        faa: "ECK OH",          ipa: "" },
  f: { codeword: "foxtrot",     faa: "FOKS TROT",       ipa: "" },
  g: { codeword: "golf",        faa: "GOLF",            ipa: "" },
  h: { codeword: "hotel",       faa: "HOH TELL",        ipa: "" },
  i: { codeword: "india",       faa: "IN DEE AH",       ipa: "" },
  j: { codeword: "juliett",     faa: "JEW LEE ETT",     ipa: "" },
  k: { codeword: "kilo",        faa: "KEY LOH",         ipa: "" },
  l: { codeword: "lima",        faa: "LEE MAH",         ipa: "" },
  m: { codeword: "mike",        faa: "MIKE",            ipa: "" },
  n: { codeword: "november",    faa: "NO VEM BER",      ipa: "" },
  o: { codeword: "oscar",       faa: "OSS CUR",         ipa: "" },
  p: { codeword: "papa",        faa: "PAH PAH",         ipa: "" },
  q: { codeword: "quebec",      faa: "KEH BECK",        ipa: "" },
  r: { codeword: "romeo",       faa: "ROW ME OH",       ipa: "" },
  s: { codeword: "sierra",      faa: "SEE AIR RAH",     ipa: "" },
  t: { codeword: "tango",       faa: "TANG OH",         ipa: "" },
  u: { codeword: "uniform",     faa: "YOU NEE FORM",    ipa: "" },
  v: { codeword: "victor",      faa: "VIK TAH",         ipa: "" },
  w: { codeword: "whiskey",     faa: "WISS KEY",        ipa: "" },
  x: { codeword: "x-ray",       faa: "ECKS RAY",        ipa: "" },
  y: { codeword: "yankee",      faa: "YANG KEY",        ipa: "" },
  z: { codeword: "zulu",        faa: "ZOO LOO",         ipa: "" },
  1: { codeword: "UNAONE",      faa: "OO-NAH-WUN",      ipa: "" },
  2: { codeword: "BISSOTWO",    faa: "BEES-SOH-TOO",    ipa: "" },
  3: { codeword: "TERRATHREE",  faa: "TAY-RAH-TREE",    ipa: "" },
  4: { codeword: "KARTEFOUR",   faa: "KAR-TAY-FOWER",   ipa: "" },
  5: { codeword: "PANTAFIVE",   faa: "PAN-TAH-FIVE",    ipa: "" },
  6: { codeword: "SOXISIX",     faa: "SOK-SEE-SIX",     ipa: "" },
  7: { codeword: "SETTESEVEN",  faa: "SAY-TAY-SEVEN",   ipa: "" },
  8: { codeword: "OKTOEIGHT",   faa: "OK-TOH-AIT",      ipa: "" },
  9: { codeword: "NOVENINE",    faa: "NO-VAY-NINER",    ipa: "" },
  0: { codeword: "NADAZERO",    faa: "NAH-DAH-ZAY-ROH", ipa: "" },

  ".": {codeword: "stop", faa: "stop", ipa: "" },
  decimal: { codeword: "decimal", faa: "DAY-SEE-MAL", ipa: "" },
};

export default alphabet;