const alphabet = {
  a: { codeword: "Alpha",       faa: "<strong>al</strong>-fah",           ipa: "/ˈælfɑː/" },
  b: { codeword: "Bravo",       faa: "<strong>brah</strong> voh",         ipa: "/ˌbrɑːˈvoʊ/" },
  c: { codeword: "Charlie",     faa: "<strong>char</strong> lee",         ipa: "/ˈtʃɑːrliː/" },
  d: { codeword: "Delta",       faa: "<strong>dell</strong> tah",         ipa: "/ˈdɛltɑː/" },
  e: { codeword: "Echo",        faa: "<strong>eck</strong> oh",           ipa: "/ˈɛkoʊ/" },
  f: { codeword: "Foxtrot",     faa: "<strong>foks</strong> trot",        ipa: "/ˈfɒkstrɒt/" },
  g: { codeword: "Golf",        faa: "<strong>golf</strong>",             ipa: "/ˈɡɒlf/" },
  h: { codeword: "Hotel",       faa: "hoh <strong>tell</strong>",         ipa: "/hoʊˈtɛl/" },
  i: { codeword: "India",       faa: "<strong>in</strong> dee ah",        ipa: "/ˈɪndiːɑː/" },
  j: { codeword: "Juliett",     faa: "<strong>jew</strong> lee ett",      ipa: "/ˈdʒuːliːɛt/" },
  k: { codeword: "Kilo",        faa: "<strong>key</strong> loh",          ipa: "/ˈkiːloʊ/" },
  l: { codeword: "Lima",        faa: "<strong>lee</strong> mah",          ipa: "/ˈliːmɑː/" },
  m: { codeword: "Mike",        faa: "<strong>mike</strong>",             ipa: "/ˈmaɪk/" },
  n: { codeword: "November",    faa: "no <strong>vem</strong> ber",       ipa: "/noʊˈvɛmbər/" },
  o: { codeword: "Oscar",       faa: "<strong>oss</strong> cur",          ipa: "/ˈɒskɑː/" },
  p: { codeword: "Papa",        faa: "pah <strong>pah</strong>",          ipa: "/pɑːˈpɑː/" },
  q: { codeword: "Quebec",      faa: "keh <strong>beck</strong>",         ipa: "/kɛˈbɛk/" },
  r: { codeword: "Romeo",       faa: "<strong>row</strong> me oh",        ipa: "/ˈroʊmiːoʊ/" },
  s: { codeword: "Sierra",      faa: "see <strong>air</strong> rah",      ipa: "/siːˈɛrɑː/" },
  t: { codeword: "Tango",       faa: "<strong>tang</strong> oh",          ipa: "/ˈtæŋɡoʊ/" },
  u: { codeword: "Uniform",     faa: "<strong>you</strong> nee form",     ipa: "/ˈuːniːfɔːrm/" },
  v: { codeword: "Victor",      faa: "<strong>vik</strong> tah",          ipa: "/ˈvɪktɑː/" },
  w: { codeword: "Whiskey",     faa: "<strong>wiss</strong> key",         ipa: "/ˈwɪskiː/" },
  x: { codeword: "X-ray",       faa: "<strong>ecks</strong> ray",         ipa: "/ˌɛksˈreɪ/" },
  y: { codeword: "Yankee",      faa: "<strong>yang</strong> key",         ipa: "/ˈjæŋkiː/" },
  z: { codeword: "Zulu",        faa: "<strong>zoo</strong> loo",          ipa: "/ˈzuːluː/" },

  0: { codeword: "Zero",        faa: "<strong>ze</strong> ro",            ipa: "/ˈziːroʊ/" },
  1: { codeword: "One",         faa: "<strong>wun</strong>",              ipa: "/ˈwʌn/" },
  2: { codeword: "Two",         faa: "<strong>too</strong>",              ipa: "/ˈtuː/" },
  3: { codeword: "Three",       faa: "<strong>tree</strong>",             ipa: "/ˈtriː/" },
  4: { codeword: "Four",        faa: "<strong>fow</strong> er",           ipa: "/ˈfoʊ.ər/" },
  5: { codeword: "Five",        faa: "<strong>fife</strong>",             ipa: "/ˈfaɪf/" },
  6: { codeword: "Six",         faa: "<strong>six</strong>",              ipa: "/ˈsɪks/" },
  7: { codeword: "Seven",       faa: "<strong>sev</strong> en",           ipa: "/ˈsɛvɛn/" },
  8: { codeword: "Eight",       faa: "<strong>ait</strong>",              ipa: "/ˈeɪt/" },
  9: { codeword: "Nine",        faa: "<strong>nin</strong> er",           ipa: "/ˈnaɪnər/" },

  ".": {codeword: "Stop",       faa: "stop",                              ipa: "/ˈstɒp/" },
  decimal: { codeword: "Decimal", faa: "day see mal",                     ipa: "/ˌdeɪˌsiːˈmæl/" },
};

export default alphabet;